### ISSUE TITLE
too many resets while synchronising (30)

### ISSUE THREAD

**Issue by qbossard** [themainframe/leptonic#2]
i did everything advised including changing the spidev bufsiz, yet i have the following output.

```pi@raspberrypi:~/leptonic $ ./bin/examples/fb_video /dev/spidev0.0
17:44:31 INFO  examples/fb_video.c:264: preallocating space for segments...
17:44:31 INFO  examples/fb_video.c:272: Creating get_frames_from_device_thread thread
17:44:31 INFO  examples/fb_video.c:278: Creating draw_frames_to_fb_thread thread
17:44:31 INFO  examples/fb_video.c:57: opening SPI device... /dev/spidev0.0
17:44:31 INFO  examples/fb_video.c:72: aquiring VoSPI synchronisation
17:44:31 INFO  examples/fb_video.c:163: framebuffer spec: 160x120, 24 bpp, lsize: 1152000, llen: 2400
17:44:31 WARN  src/api/vospi.c:105: packet 20 ID was 0 - deasserting CS & waiting to reset...
[...]
17:44:37 WARN  src/api/vospi.c:105: packet 20 ID was 0 - deasserting CS & waiting to reset...
17:44:37 ERROR src/api/vospi.c:109: too many resets while synchronising (30)
17:44:37 ERROR examples/fb_video.c:75: failed to obtain frame from device.
```

any hint/pointer?

fwiw i also tried various `LeptonModule` execs, all w/o success. i must be doing something wrong...

**Comment by themainframe** [comment]
Been a long time since I worked on this I'm afraid, but from that it looks like you're never seeing anything other than 0s. Do you have a scope you could take a look at the SPI data lines with? Could you reduce the SPI speed perhaps in case you're running into signal integrity issues (https://github.com/themainframe/leptonic/blob/master/src/leptonic.c#L57)?

**Comment by qbossard** [comment]
thanks for your answer. yes i bet it's rather old stuff for you :)

i just ordered it and am very frustrated. i don't have a scope but maybe there's a way to dump spi data -- i'll have a look.
this is beyond my expertise but: should i expect data to flow on MOSI MISO as soon as the board is powered up?

i'll try slower freqs as well. any you recommend in particular? do i only need to edit line 57 adn re-compile?

**Comment by qbossard** [comment]
my (temporary & unsatisfactory) solution (for the likes):
https://github.com/lukevanhorn/Lepton3/blob/master/capture/capture.c
i managed to make it work and get pics -- conclusion is the setup and hardware work.

**Comment by qbossard** [comment]
worked on raspi zero although dropping lots of frames
